name: pytest

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: pytest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.10"

      - name: Sync dependencies
        run: uv sync --group dev

      - name: Run pytest
        run: uv run pytest
